program: main_tdc.py
command:
  - python
  - main_tdc.py
  - --wandb
  - --save_path
  - "results/"
  - --arch
  - "HPS"
  - --epochs
  - "250"
  - --train-batch-size
  - "1024"
  - --lr-factor
  - "0.9"
  - --loss-reduction
  - "sum"
  - --lr
  - "0.0002"
  - --model-encoder-channels
  - "128"
  - --model-encoder-num-layers
  - "5"
  - --model-decoder-channels
  - "64"
  - --model-decoder-num-layers
  - "1"
  - --model-decoder-dropout
  - "0.3"
  - ${args}
method: grid

metric:
  name: test/average_rank
  goal: minimize

parameters:
  more_tasks:
    values: [True, False]
  weighting:
    values: ["DB_MTL", "FairGrad", "EW"]
  seed:
    values: [0, 1, 2]
