program: main_tdc.py
command:
  - python
  - main_tdc.py
  - --wandb
  - --arch
  - "HPS"
  - --epochs
  - "200"
  - --train-batch-size
  - "2048"
  - --lr-factor
  - "0.9"
  - --loss-reduction
  - "sum"
  - --lr
  - "0.0002"
  - --model-encoder-channels
  - "128"
  - --model-encoder-num-layers
  - "5"
  - --model-decoder-channels
  - "64"
  - --model-decoder-num-layers
  - "1"
  - --model-decoder-dropout
  - "0.3"
  - ${args}
method: grid

metric:
  name: test/average_rank
  goal: minimize

parameters:
  weighting:
    values: [
      'EW',
      'GradNorm',
      'UW',
      'MGDA',
      'DWA', 
      'GLS',
      'PCGrad',
      # 'GradDrop',
      # 'IMTL',
      'GradVac',
      'CAGrad',
      # 'Nash_MTL',
      'RLW',
      'MoCo',
      'Aligned_MTL', 
      'STCH',
      'ExcessMTL',
      'FairGrad',
      'DB_MTL',
      'FAMO',
      # 'MoDo',
      # 'SDMGrad',
    ]
  seed:
    values: [0, 1, 2]