program: main_tdc.py
command:
  - python
  - main_tdc.py
  - --wandb
  - --save_path
  - "results/"
  - --weighting
  - "FairGrad"
  - --FairGrad-alpha
  - "0.5"
  - --arch
  - "HPS"
  - --epochs
  - "500"
  - --train-batch-size
  - "1024"
  - --lr-factor
  - "0.9"
  - --loss-reduction
  - "sum"
  - --lr
  - "0.0005"
  - --lr-factor
  - "0.85"
  - --model-encoder-channels
  - "256"
  - --model-encoder-num-layers
  - "5"
  - --model-encoder-dropout
  - "0.3"
  - --model-decoder-channels
  - "64"
  - --model-decoder-num-layers
  - "1"
  - --model-decoder-dropout
  - "0.3"
  - ${args}
method: grid

metric:
  name: test/average_rank_last
  goal: minimize

parameters:
  seed:
    values: [0, 1, 2]
