program: main_tdc.py
command:
  - python
  - main_tdc.py
  - --wandb
  - --weighting
  - "DB_MTL"
  - --epochs
  - "150"
  - --train-batch-size
  - "1028"
  - ${args}
method: grid

metric:
  name: test/average_rank
  goal: minimize

parameters:
  arch:
    values: [
      'HPS',
      'CGC',
      'Cross_stitch',
      'DSelect_k',
      'LTB',
      'MMoE',
      'MTAN',
      'PLE'
    ]