program: main_tdc.py
command:
  - python
  - main_tdc.py
  - --save_path
  - "results/"
  - --wandb
  - --weighting
  - "FairGrad"
  - --arch
  - "HPS"
  - --epochs
  - "200"
  - --loss-reduction
  - "sum"
  - --train-batch-size
  - "1028"
  - --model-decoder-channels
  - "64"
  - --model-decoder-num-layers
  - "1"
  - --model-decoder-dropout
  - "0.3"
  - ${args}
method: grid

metric:
  name: test/average_rank
  goal: minimize

parameters:
  lr:
    values: [0.00009, 0.0002, 0.0005]
  lr-factor:
    values: [0.85, 0.9, 0.95]
  seed:
    values: [0, 1, 2]